config/routes.rb
Bookit::Application.routes.draw do
  resources :users
  resources :sessions, only: [ :new, :create, :destroy ]
  resources :book_posts, only: [:create, :destroy ]
  resources :book_bites, only: [:create, :destroy ]
  
  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'

end

app/models/book_bite.rb
class BookBite < ActiveRecord::Base
  attr_accessible :bite
  belongs_to :user
  
  validates :user_id, presence: true
  validates :bite, presence: true, length: { maximum: 140 }
  
  default_scope order: 'book_bites.created_at DESC'
end

app/models/book_post.rb
class BookPost < ActiveRecord::Base
  attr_accessible :title, :subtitle, :genre, :summary, :date
  
  belongs_to :user
  
  validates :title, presence: true, length: { maximum: 50 }
  validates :subtitle, length: { maximum: 50 }
  validates :genre, length: { maximum: 30 }
  validates :summary, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true
  
  default_scope order: 'book_posts.created_at DESC'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation, :city, :state, :writer
  has_secure_password
  has_many :book_posts, dependent: :destroy
  has_many :book_bites, dependent: :destroy
  
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 50 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  
  def feed
    BookPost.where("user_id = ?", id)
  end
  
  private 
    
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/book_posts_controller.rb
class BookPostsController < ApplicationController
  before_filter :signed_in_user,  only: [:create, :destroy]
  before_filter :correct_user,    only: :destroy

  def create
    @book_post = current_user.book_posts.build(params[:book_post])
    if @book_post.save
      flash[:success] = 'Your book post has been created!'
      redirect_to root_path
    else
      @book_post_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @book_post.destroy
    redirect_back_or root_path
  end
  
  private
  
    def correct_user
      @book_post = current_user.book_posts.find_by_id(params[:id])
      redirect_to root_path if @book_post.nil?
    end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
  
end

def create
  user = User.find_by_email(params[:session][:email])
  if user && user.authenticate(params[:session][:password])
    # Sign the user in and redirect to the user's show page.
    sign_in user
    redirect_back_or user
  else
    # Render the sign-in page again.
    flash.now[:error] = 'You\'ve entered an invalid e-mail/password combination.'
    render 'new'
  end
end

def destroy
  sign_out
  redirect_to root_path
end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @book_post = current_user.book_posts.build
      @book_post_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user,  only: [ :index, :edit, :update ]
  before_filter :correct_user,    only: [ :edit, :update ]
  before_filter :admin_user,      only: :destroy 
  
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
    @book_posts = @user.book_posts
    @book_bites = @user.book_bites.paginate(page: params[:page])
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      # Handle a successful save.
      sign_in @user
      flash[:success] = 'Congrats on becoming a BookBits member!'
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Your profile has been updated."
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'This BookBits Member has been deleted.'
    redirect_to users_path
  end
  
  private
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end
    
  def current_user=(user)
    @current_user=user
  end
  
  def current_user
    @current_user ||= user_from_remember_token
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in."
    end
  end
  
  def sign_out
    current_user = nil
    cookies.delete(:remember_token)
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end
  
  def store_location
    session[:return_to] = request.fullpath
  end
  
  private
  
    def user_from_remember_token
      remember_token = cookies[:remember_token]
      User.find_by_remember_token(remember_token) unless remember_token.nil?
    end
    
    def clear_return_to
      session.delete(:return_to)  
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_bites/_book_bite.html.erb
<li>
  <span class="content">
		<%= book_bite.bite %>	
	</span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(book_bite.created_at) %> ago.
  </span>
	<% if current_user?(book_bite.user) %>
		<% link_to 'Delete', book_bite, method: :delete,
																		confirm: 'Sure about that?',
																		title: book_bite.bite %>
	<% end %>
</li>

app/views/book_posts/_book_post.html.erb
<li>
  <span class="content">
		<!--List all of your book posts.-->
		<b><%= book_post.title.upcase %></b>
		<br>				
		<% if book_post.subtitle %>
			<%= book_post.subtitle %>
			<br/>
		<% end %>	
		<% if book_post.genre %>
			<%= book_post.genre %>
			<br/>
		<% end %>
		<%= book_post.summary %>		
	</span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(book_post.created_at) %> ago.
  </span>
	<% if current_user?(book_post.user) %>
		<% link_to 'Delete', book_post, method: :delete,
																		confirm: 'Sure about that?',
																		title: book_post.title %>
	<% end %>
</li>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
		BookBits by
    <a href="http://emilyellison986.github.com/">Emily Ellison</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "BookBits", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
					<% if signed_in? %>
						<li><%= link_to 'Members', users_path %></li>
						<li id='fat-menu' class='dropdown'>
							<a href='#' class='dropdown-toggle' data-toggle='dropdown'>
								Account<b class='caret'></b>
							</a>
							<ul class='dropdown-menu'>
								<li><%= link_to 'Profile', current_user %></li>
								<li><%= link_to 'Update Your Profile', edit_user_path(current_user) %></li>
								<li><%= link_to 'Privacy Settings', '#' %></li>
								<li class='divider'></li>
								<li><%= link_to 'Sign Out', signout_path, method: 'delete' %></li>
							</ul>
						</li>
					<% else %>
          	<li><%= link_to "Sign In", signin_path %></li>
        	<% end %>
				</ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookBits <%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
 		<%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
			<% flash.each do |key, value| %>
			  <div class="alert alert-<%= key %>"><%= value %></div>
			<% end %>
      <%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_book_post.html.erb
<% if @book_post_items.any? %>
	<ol class='microposts'>
		<%= render partial: 'shared/book_post_item', collection: @book_post_items %>
	</ol>
	<%= will_paginate @book_post_items %>
<% end %>

app/views/shared/_book_post_form.html.erb
<%= form_for(@book_post) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="accordion" id="accordion2">
     <div class="accordion-group">
       <div class="accordion-heading">
         <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
           	Post a Book
         </a>
       </div>
       <div id="collapseOne" class="accordion-body collapse">
         <div class="accordion-inner">
						<%= f.label :title, 'Title' %>
						<%= f.text_field :title %>
						<%= f.label :subtitle, 'Sub-title' %>
						<%= f.text_field :subtitle %>
						<%= f.label :genre, 'Genre' %>
						<%= f.text_field :genre %>
						<%= f.label :summary, 'Summary' %>
						<%= f.text_area :summary %>
						<br/><br/>
						<%= f.submit 'Post', class: 'btn btn-large btn-primary' %>
         </div>
       </div>
     </div>
	</div>

<% end %>

app/views/shared/_book_post_item.html.erb
<li id="<%= book_post_item.id %>">
	<span class='user'>
		<%= link_to book_post_item.user.name, book_post_item.user %>
	</span>
	<span class='content'>
		<!--List all of your book posts.-->
		<b><%= book_post_item.title.upcase %></b>
		<br>				
		<% if book_post_item.subtitle %>
			<%= book_post_item.subtitle %>
			<br/>
		<% end %>	
		<% if book_post_item.genre %>
			<%= book_post_item.genre %>
			<br/>
		<% end %>
		<%= book_post_item.summary %>
	</span>	
	<span class='timestamp'>
		Posted <%= time_ago_in_words(book_post_item.created_at) %> ago.
	</span>	
	<% if current_user?(book_post_item.user) %>
		<%= link_to "Delete", book_post_item, method:  :delete,
	                                   confirm: "Sure about that?",
	                                   title:   book_post_item.title %>
  <% end %>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class='microposts'>
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	<span class='user'>
		<%= link_to feed_item.user.name, feed_item.user %>
	</span>
	<span class='content'>
		<!--List all of your book posts.-->
		<b><%= feed_item.title.upcase %></b>
		<br>				
		<% if feed_item.subtitle %>
			<%= feed_item.subtitle %>
			<br/>
		<% end %>	
		<% if feed_item.genre %>
			<%= feed_item.genre %>
			<br/>
		<% end %>
		<%= feed_item.summary %>
	</span>	
	<span class='timestamp'>
		Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
	</span>	
	<% if current_user?(feed_item.user) %>
		<%= link_to "Delete", feed_item, method:  :delete,
	                                   confirm: "Sure about that?",
	                                   title:   feed_item.title %>
  <% end %>
</li>

app/views/shared/_user_info.html.erb
<h1>
	<a href="<%= user_path(current_user) %>"><%= current_user.name %></a>
</h1>
<span>
	<%= link_to 'View My Profile', current_user %>
</span>
<span>
	book <%= pluralize(current_user.book_posts.count, "post") %>
</span>

app/views/static_pages/about.html.erb
<% provide(:title,'| About')%>
<h1>About</h1>
<h2>BookBits was made for (and by) passionate, disorganized readers.</h2>

app/views/static_pages/help.html.erb
<% provide(:title,'| Help')%>
<h1>Help</h1>

app/views/static_pages/home.html.erb
<% provide(:title, ' ') %>
<% if signed_in? %>
	<div class='row'>
		<aside class='span4'>
			<section>
				<%= render 'shared/user_info' %>
			</section>
			<section>
				<%= render 'shared/book_post_form' %>
			</section>
		</aside>
		<div class='span8'>
			<h3>Book Post Feed</h3>
			<%= render 'shared/book_post' %>
		</div>
	</div>
<% else %>
	<div class='center hero-unit'>
		<h1>Welcome to BookBits.</h1>
		<h2>
			Follow your favorite authors.<br/>
			Keep a calendar of upcoming releases.<br/>
			Get access to their latest press coverage.
		</h2>
	
		<%= link_to "Sign up for BookBits", signup_path, 
		  	class: "btn btn-large btn-primary" %>
	</div>
<% end %>

app/views/users/_profile_info.html.erb
<p>
	
	<% if @user.writer %>
		Author
	<% end %>
	
</p>	
<p>	
	
	<!--Show city and state only if they're available-->
	
	<% if !@user.city.blank? && !@user.state.blank? %>			
		<%= @user.city %>, <%= @user.state %>			
	<% elsif !@user.city.blank? && @user.state.blank? %>
		<%= @user.city %>			
	<% elsif @user.city.blank? && !@user.state.blank? %>
		<%= @user.state %>
	<% else %>
	<% end %>

</p>

app/views/users/_user.html.erb
<li>
	<%= link_to user.name, user %>
	<% if current_user.admin? && !current_user?(user) %>
		| <%= link_to 'Delete', user, method: :delete, confirm: 'Sure about that?' %>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Update Your Profile') %>
<h1>Update Your Profile</h1>

<div class='row form-vertical'>
	<div class='span6 offset3'>
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
			<h3>Account Information</h3>
			<br/>
				<%= f.label :name %>
				<%= f.text_field :name %>
			
				<%= f.label :email, 'E-mail' %>
				<%= f.text_field :email %>
			<hr/>
			<h3>Membership</h3>
			<br/> 
				<%= f.label :writer, 'Author', class: 'checkbox inline'%>
				<%= f.check_box :writer %>
			<br/>
			<hr/>
			<h3>Location</h3>
			<br/> 
				<%= f.label :city %>
				<%= f.text_field :city %>
				<%= f.label :state %>
				<%= f.text_field :state %>
			<hr/>
			<h3>Verify your profile updates.</h3>
			<br/>
				<%= f.label :password %>
				<%= f.password_field :password %>			
				<%= f.label :password_confirmation, 'Confirm Password' %>
				<%= f.password_field :password_confirmation %>
			<br/>
			<br/>
			<%= f.submit 'Save Changes', class: 'btn btn-large btn-primary' %>
			
		<% end %>
	</div>
</div>

app/views/users/index.html.erb
<%= provide(:title, '| Members') %>
<h1>Members</h1>

<%= will_paginate %>

<ul class='users'>
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, '| Sign Up')%>
<h1>Sign Up</h1>
<div class='row'>
	<div class='span6 offset3'>
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
		
			<%= f.label :name %>
			<%= f.text_field :name %>
			
			<%= f.label :email, 'E-mail'%>
			<%= f.text_field :email %>
			
			<%= f.label :password %>
			<%= f.password_field :password %>
			
			<%= f.label :password_confirmation, 'Confirm Password' %>
			<%= f.password_field :password_confirmation %>
			
			<%= f.label :writer, 'Author' %>
			<%= f.check_box :writer %>
			
			<br/><br/>
			<%= f.submit 'Create My Account', class: 'btn btn-large btn-primary' %>
		<% end %>
	</div>
</div>	

app/views/users/show.html.erb
<% provide(:title, "| #{@user.name}") %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= @user.name %>
      </h1>
			<%= render 'profile_info' %>
    </section>
		<section>
			<% if @user.book_posts.any? %>
				<h3>Books</h3>
				<ol class='microposts'>
					<%= render @book_posts %>
				</ol>
			<% end %>
		</section>
  </aside>

	<div class='span8'>
		<% if @user.book_bites.any? %>
			<h3>Book Bites (<%= @user.book_bites.count %>)</h3>
			<ol class='microposts'>
				<%= render @book_bites %>
			</ol>
			<%= will_paginate @book_bites %>
		<% end %>
	</div>
</div>